dir_main := $(shell dirname $(shell readlink -fe $(lastword ${MAKEFILE_LIST})))

# ubuntu
TEXLIVE_DIR := "/opt/texlive/2023"
TEXLIVE_FONT_DIR := "/usr/share/fonts/opentype/noto/"
SHELL := /usr/bin/env bash

include $(dir_main)/../../common.mk

